import torch
from torch.distributions import Exponential


def simulate_step_gpu(current_states_idx, Q):
    """
    Simulates the next jump for an entire BATCH of matches simultaneously.
    current_states_idx: A 1D tensor of length N (e.g., 10,000) containing the current state indices.
    Q: The 51x51 transition matrix tensor.
    """
    batch_size = current_states_idx.shape[0]

    # Q[i] is a vector of the rates of jumping to all other states from state i
    # we clone it because we're going to modify it in place later and we don't want to change Q
    # for each row, we find out 'what are my next moves and how often do they happen?'
    # rates is 10k rows and 240 columns
    rates = Q[current_states_idx].clone()

    # gets the total negative sum of all the rates (the total exit rate)
    q_ii = rates.gather(1, current_states_idx.unsqueeze(1)).squeeze(1)

    # checks if the system is stuck and unable to lave the current state
    valid_mask = torch.abs(q_ii) > 1e-8

    # set it so that by default, no change happens
    # this is so that states that fail the valid_mask just don't change
    dt = torch.full((batch_size,), 9999.0, device=Q.device)
    next_states_idx = current_states_idx.clone()
    # if there are any valid states, work with those
    if valid_mask.any():
        valid_q_ii = q_ii[valid_mask]
        exit_rates = -valid_q_ii
        # PyTorch's exponential function uses the rate not the scale, so we can put rates directly in here
        # unlike with numpy's exponential function
        # dist is distribution
        dist = Exponential(exit_rates)
        # select a random value generated by the exponential rv?
        # we set dts for each universe to be a random sample from the Exponential distribution based on the
        # exit rate.
        # and we only change the dts that are valid, hence the [valid_mask]
        dt[valid_mask] = dist.sample()
        # this just gets the valid rates
        valid_rates = rates[valid_mask]

        current_valid_idx = current_states_idx[valid_mask].unsqueeze(1)
        valid_rates.scatter_(1, current_valid_idx, 0.0)

        jump_probs = valid_rates / exit_rates.unsqueeze(1)
        jump_probs = torch.clamp(jump_probs, min=0.0)

        prob_sums = jump_probs.sum(dim=1, keepdim=True)
        safe_prob_sums = torch.where(
            prob_sums > 0, prob_sums, torch.ones_like(prob_sums)
        )
        jump_probs = jump_probs / safe_prob_sums

        valid_next_states = torch.multinomial(jump_probs, num_samples=1).squeeze(1)

        next_states_idx[valid_mask] = valid_next_states

    return next_states_idx, dt


def run_monte_carlo_gpu(
    initial_state_str, device, state_to_idx, idx_to_state, Q_tensor, n_simulations=10000
):

    # 1. Initialize 10,000 parallel universes
    initial_idx = state_to_idx[initial_state_str]
    current_states = torch.full(
        (n_simulations,), initial_idx, dtype=torch.long, device=device
    )
    current_times = torch.zeros(n_simulations, dtype=torch.float32, device=device)

    end_time = 5400.0  # 90 minutes

    # 2. The Time Mask
    active_mask = current_times < end_time

    # 3. The Parallel Physics Loop
    while active_mask.any():
        # Only simulate the universes where the clock hasn't run out
        active_states = current_states[active_mask]

        # Hit the GPU
        next_states, dt = simulate_step_gpu(active_states, Q_tensor)

        # Advance the clocks and move the balls
        current_times[active_mask] += dt
        current_states[active_mask] = next_states

        # Safety Trap: If any universes hit an absorbing state, force them past 90 mins so they drop out
        stuck_mask = dt > 9000.0
        if stuck_mask.any():
            # Update the specific times of the stuck universes within the active subset
            active_times_subset = current_times[active_mask]
            active_times_subset[stuck_mask] += 9999.0
            current_times[active_mask] = active_times_subset

        # Re-evaluate who is still playing
        active_mask = current_times < end_time

    # 4. The Final Whistle (Parse the Results)
    results = {"Win": 0, "Draw": 0, "Loss": 0}

    # Bring the final state integers back to the CPU to parse the strings
    final_states_cpu = current_states.cpu().numpy()

    for final_idx in final_states_cpu:
        final_state_str = idx_to_state[final_idx]
        delta_g = int(final_state_str.split("_")[0].replace("G:", ""))

        if delta_g > 0:
            results["Win"] += 1
        elif delta_g < 0:
            results["Loss"] += 1
        else:
            results["Draw"] += 1

    return {k: v / n_simulations for k, v in results.items()}
